security:
  oauth2:
    client:
      client-id: ClientId
      client-secret: secret
      scope: read, write
      auto-approve-scopes: .*
      authorized-grant-types: authorization_code
    authorization:
      check-token-access: permitAll()

logging:
  level:
    org.springframework.security: DEBUG
client:
  url: http://localhost:8081/ui